version: "3.8"

services:
  storage:
    image: mongo:7.0.1-rc0
    container_name: storage
    ports:
      - 27017:27017

  broker:
    container_name: broker
    image: redis:alpine3.18
    command: redis-server
    ports:
      - 6379:6379
